name: yasulin
version: '1.0'
main: org.yasu.yasulin.Yasulin
api-version: '1.21'
load: STARTUP
authors: [ yasu ]
description: my first ever plugin lmao disaster
commands:
  pearlshot:
    description: give player the Pearl Shot bow
  settings:
    description: what should i put here